### ISSUE TITLE
catch error in forming experiment

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#37]
exp = e.operate.simple_clf(np.array([[1,1,1],[1,2,3]]), np.array([1,1]),RandomForestClassifier())

catch mistype errors

**Comment by zar1** [comment]
For example, this will throw an error because the third argument should be something like:

`{RandomForestClassifier: {}}` rather than `RandomForestClassifier()`

**Comment by zar1** [comment]
subsumed by diogenes iss 7 https://github.com/dssg/diogenes/issues/7
