### ISSUE TITLE
decide if exp.train() makes any sense

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#38]
do we think that a single run should be supported by experiment class?
At one point i was confident but slowly am growing less so.

The argument against is clear.  wrapping a clf with no convience or sugar is a bit silly.

The converse is also true, why bifurcate the workflow for a simple and often used case.
Sklearn uses y_predicted, y_true as standard...

should exp.clf.train() exist?  does this make any sense in our formulation? I can't see how it would...

**Comment by zar1** [comment]
If the user wants to do an experiment of one run, they can with the current interface, but I don't think there's any reason to make a special case out of it.
