### ISSUE TITLE
rough draft of classifers to add..   with base configerurations

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#47]
RidgeClassifier:{'tol':[1e-2], 'solver':['lsqr']},
       SGDClassifier:{'alpha':[.0001], 'n_iter':[50],'penalty':['l1', 'l2', 'elasticnet'])}
       Perceptron:{'n_iter':[50])},
       PassiveAggressiveClassifier:{'n_iter':[50]}
       BernoulliNB:{'alpha':[.01]}
       MultinomialNB:{'alpha':[.01]}
       KNeighborsClassifier:{'n_neighbors':[10]}
       NearestCentroid:{}

see:
http://scikit-learn.org/stable/auto_examples/document_classification_20newsgroups.html

note:
def benchmark(clf):

consider CMD line interface. esp for single runs from operate.

**Comment by zar1** [comment]
I have these from Rayid: https://github.com/dssg/eights/blob/rayids_clfs/eights/operate/operate.py#L99

Please remember that our interface has changed a little: Now its:

```
[{'clf': RidgeClassifier, tol':[1e-2], 'solver':['lsqr']},
...]
```

**Comment by johnsanterre** [comment]
{'clf': RidgeClassifier,'tol':[1e-2], 'solver':['lsqr']},
   {'clf': SGDClassifier,'alpha':[.0001], 'n_iter':[50],'penalty':['l1', 'l2', 'elasticnet'])},
   {'clf': Perceptron,'n_iter':[50])},
   {'clf': PassiveAggressiveClassifier,'n_iter':[50]},
   {'clf': BernoulliNB,'alpha':[.01]},
   {'clf': MultinomialNB,'alpha':[.01]},
   {'clf': KNeighborsClassifier,'n_neighbors':[10]},
   {'clf': NearestCentroid}

**Comment by zar1** [comment]
Perfect. Thank you.

**Comment by johnsanterre** [comment]
created a run_alt_classifers  just so its in the code and not an issue.
