### ISSUE TITLE
feature_pairs_in_rf should stop printing after top n results

### ISSUE THREAD

**Issue by zar1** [dssg/eights#59]
Because for forests with lots of features, there will be a looooot of output as written.

**Comment by johnsanterre** [comment]
right now we have
sorted_top_feat_importance(self, n)

where n = number of top features.

I'll change that to a default of 25.

**Comment by zar1** [comment]
I like that convention. If a function returns "top n of something" it always has an argument called "n" with a default argument.

**Comment by zar1** [comment]
Fixed in e7adcd04b30110098b4bf2c74d99aad7c87bfd56
