### ISSUE TITLE
col_names and names standarization

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#75]
cast_np_nd_to_sa(nd, dtype=None, names=None):
cast_list_of_list_to_sa(L, col_names=None, dtype=None):

prob just remove cast_list...

**Comment by zar1** [comment]
Let's not remove cast_list_of_list_to_sa. The two functions do different things. Also, see #63

**Comment by johnsanterre** [comment]
Agreed.

**Comment by johnsanterre** [comment]
We did compared to what i expected.
