### ISSUE TITLE
cast_np_nd_to_sa throws error when names provided by not dtypes.

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#76]
cast_np_nd_to_sa(np.array([x[:-1] for x in data[1:]],dtype='float'), names=col_names)

Traceback (most recent call last):
  File "test_wine.py", line 28, in <module>
    M = cast_np_nd_to_sa(np.array([x[:-1] for x in data[1:]],dtype='float'), names=col_names)
  File "/Users/ciphernetic/Dropbox/code/eights/eights/utils.py", line 240, in cast_np_nd_to_sa
    'formats': [nd_dtype for i in xrange(n_cols)]})
ValueError: 'names', 'formats', 'offsets', and 'titles' dicct entries must have the same length

**Comment by johnsanterre** [comment]
if all(dtype[i] == nd_dtype for i in xrange(len(dtype))):
        return nd.reshape(nd.size).view(dtype)

**Comment by zar1** [comment]
I'm not sure what to do about that. dtypes for structured arrays need to be
of the form [(col_name, type), (col_name, type), ...]. It makes sense that
using a single dtype doesn't work. We could support this, but it's
nontrivial.

On Tue, Sep 22, 2015 at 8:19 AM, John Santerre <notifications@github.com>
wrote:

> if all(dtype[i] == nd_dtype for i in xrange(len(dtype))):
>     return nd.reshape(nd.size).view(dtype)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dssg/eights/issues/76#issuecomment-142287264>.
>



-- 
Sent from my generic Linux box

**Comment by johnsanterre** [comment]
I don't think thats it, this is the bug i am working on right now.  

this Fails as dtype
dtype([('fixed acidity', '<f8'), ('volatile acidity', '<f8'), ('citric acid', '<f8'), ('residual sugar', '<f8'), ('chlorides', '<f8'), ('free sulfur dioxide', '<f8'), ('total sulfur dioxide', '<f8'), ('density', '<f8'), ('pH', '<f8'), ('sulphates', '<f8'), ('alcohol', '<f8'), ('quality', '<f8')])

**Comment by zar1** [comment]
Ah. I misread your example. Sorry about that.

**Comment by johnsanterre** [comment]
Durp.

**Comment by zar1** [comment]
After further investigation, this was because len(col_names) > (the number of columns in our nd array). 

When the user passes objects with incompatible shapes, we should provide a friendlier error than the one above.

**Comment by zar1** [comment]
Subsumed by https://github.com/dssg/diogenes/issues/7
