### ISSUE TITLE
fix open_csv_as_structured_array to accomodate ,'s in strings

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#9]
userName, "something, that requires, commas", 3
userName, "something, that requires, commas", 3
userName, "something, that requires, commas", 3

need to be able to push this thru open_csv_as_structured_array
doesn't work because of the comma's inside the quotes.

**Comment by zar1** [comment]
Fixed in b3878b3e20deb37be8c5c273b82a6216ca7f7adc
